# SPDX-FileCopyrightText: 2024 Frans van Dorsselaer
#
# SPDX-License-Identifier: GPL-3.0-only

---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  REUSE:
    permissions:
      contents: read
    uses: crisnsz/workflows/.github/workflows/REUSE.yml@main

  MegaLinterNET:
    permissions:
      contents: read
      pull-requests: write
    uses: crisnsz/workflows/.github/workflows/mega-linter-dotnet.yml@main
